# Generated by Django 5.2.7 on 2026-08-29 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitacoras', '0009_bitacoraviaje_cliente_2_and_more'),
        ('modulacion', '0005_agencia_email_contacto'),
        ('operadores', '0001_initial'),
        ('unidades', '0002_unidad_control_combustible_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Naviera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('direccion_retorno', models.TextField(blank=True, verbose_name='Dirección / patio de retorno')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Naviera',
                'verbose_name_plural': 'Navieras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('numero_contenedor', models.CharField(choices=[('1', 'Contenedor 1'), ('2', 'Contenedor 2')], default='1', max_length=1, verbose_name='Contenedor del viaje')),
                ('contenedor', models.CharField(max_length=50, verbose_name='Contenedor')),
                ('tipo_contenedor', models.CharField(choices=[('20', '20 pies'), ('40', '40 pies')], default='40', max_length=2, verbose_name='Tipo de contenedor')),
                ('estado', models.CharField(choices=[('POR_VACIAR', 'Por vaciar (entregado al cliente)'), ('EN_PATIO_ESPERANZA', 'En Patio Esperanza (vacío disponible)'), ('ASIGNADO', 'Operador asignado'), ('ENTREGADO_NAVIERA', 'Entregado a la naviera')], default='POR_VACIAR', max_length=20, verbose_name='Estado')),
                ('fecha_entrega_cliente', models.DateTimeField(help_text='Copiada de la bitácora; arranque del ciclo del vacío.', verbose_name='Fecha de entrega al cliente')),
                ('fecha_retorno_patio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de retorno a Patio Esperanza')),
                ('fecha_asignacion', models.DateTimeField(blank=True, help_text='Se sella la primera vez que se asigna unidad y operador.', null=True, verbose_name='Fecha de asignación')),
                ('fecha_compromiso_naviera', models.DateTimeField(blank=True, null=True, verbose_name='Fecha compromiso de entrega a naviera')),
                ('fecha_salida_naviera', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de salida rumbo a la naviera')),
                ('fecha_entrega_naviera', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega a la naviera')),
                ('tiene_retraso', models.BooleanField(default=False, verbose_name='Tiene retraso')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(blank=True, help_text='Destino del aviso de retraso. Se auto-llena si el viaje vino de Modulación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacios', to='modulacion.agencia', verbose_name='Agencia aduanal')),
                ('bitacora_viaje', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacios', to='bitacoras.bitacoraviaje', verbose_name='Bitácora de viaje')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacios', to='bitacoras.cliente', verbose_name='Cliente')),
                ('naviera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacios', to='vacios.naviera', verbose_name='Naviera')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacios', to='operadores.operador', verbose_name='Operador asignado')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacios', to='unidades.unidad', verbose_name='Unidad asignada')),
            ],
            options={
                'verbose_name': 'Vacío',
                'verbose_name_plural': 'Vacíos',
                'ordering': ['-fecha_entrega_cliente'],
            },
        ),
        migrations.CreateModel(
            name='RetrasoVacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANIOBRA', 'Cambio por maniobra (retraso en la entrega)'), ('RETORNO', 'Retraso de retorno (viaje de regreso)')], max_length=10, verbose_name='Tipo de retraso')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('fecha_estimada_nueva', models.DateField(verbose_name='Nueva fecha estimada de entrega')),
                ('notificado_agencia', models.BooleanField(default=False, verbose_name='Notificado a la agencia')),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de notificación')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('vacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrasos', to='vacios.vacio', verbose_name='Vacío')),
            ],
            options={
                'verbose_name': 'Retraso de vacío',
                'verbose_name_plural': 'Retrasos de vacíos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CambioOperadorVacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.CharField(choices=[('NO_CONFIRMA', 'Operador no confirma'), ('SE_NIEGA', 'Operador se niega a hacer la entrega'), ('ULTIMA_HORA', 'Cambio de última hora')], max_length=15, verbose_name='Causa')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo / detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('operador_entrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operadores.operador', verbose_name='Operador entrante')),
                ('operador_saliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operadores.operador', verbose_name='Operador saliente')),
                ('unidad_entrante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='unidades.unidad', verbose_name='Unidad entrante')),
                ('unidad_saliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='unidades.unidad', verbose_name='Unidad saliente')),
                ('vacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_operador', to='vacios.vacio', verbose_name='Vacío')),
            ],
            options={
                'verbose_name': 'Cambio de operador de vacío',
                'verbose_name_plural': 'Cambios de operador de vacíos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vacio',
            constraint=models.UniqueConstraint(fields=('bitacora_viaje', 'numero_contenedor'), name='uniq_vacio_bitacora_contenedor'),
        ),
    ]
