# Generated by Django 5.2.7 on 2026-05-15 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CajaSeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=30, unique=True, verbose_name='Número económico')),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('placas', models.CharField(blank=True, max_length=20, verbose_name='Placas')),
                ('numero_serie', models.CharField(max_length=60, unique=True, verbose_name='No. de serie')),
                ('marca', models.CharField(blank=True, max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=60, verbose_name='Modelo')),
                ('anio', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2040)], verbose_name='Año')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caja Seca',
                'verbose_name_plural': 'Cajas Secas',
                'ordering': ['numero_economico'],
                'indexes': [models.Index(fields=['slug'], name='caja_seca_c_slug_88e563_idx'), models.Index(fields=['activo'], name='caja_seca_c_activo_2f98fd_idx'), models.Index(fields=['marca'], name='caja_seca_c_marca_13d3a6_idx')],
            },
        ),
    ]
