# Generated by Django 5.2.7 on 2026-04-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidad',
            name='control_combustible_total',
            field=models.BooleanField(default=False, help_text='Si está activo, esta unidad local requerirá el proceso completo de 6 pasos al cargar combustible', verbose_name='Control total de combustible'),
        ),
    ]
