# Generated by Django 5.2.7 on 2025-11-21 15:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Despachador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Despachador',
                'verbose_name_plural': 'Despachadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CargaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_litros', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad de litros cargados')),
                ('kilometraje_actual', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilometraje actual')),
                ('nivel_combustible_inicial', models.CharField(choices=[('VACIO', 'Vacío'), ('CUARTO', '1/4'), ('MEDIO', '1/2'), ('TRES_CUARTOS', '3/4'), ('LLENO', 'Lleno')], max_length=20, verbose_name='Nivel de combustible inicial')),
                ('estado_candado_anterior', models.CharField(choices=[('NORMAL', 'Normal'), ('ALTERADO', 'Alterado'), ('VIOLADO', 'Violado'), ('SIN_CANDADO', 'Sin candado')], max_length=20, verbose_name='Estado del candado anterior')),
                ('observaciones_candado', models.TextField(blank=True, verbose_name='Observaciones del candado')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio')),
                ('fecha_hora_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de finalización')),
                ('tiempo_carga_minutos', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de carga (minutos)')),
                ('foto_numero_economico', models.ImageField(upload_to='combustible/numero_economico/%Y/%m/', verbose_name='Foto número económico')),
                ('foto_tablero', models.ImageField(upload_to='combustible/tablero/%Y/%m/', verbose_name='Foto del tablero')),
                ('foto_candado_anterior', models.ImageField(upload_to='combustible/candado_anterior/%Y/%m/', verbose_name='Foto candado anterior')),
                ('foto_candado_nuevo', models.ImageField(blank=True, null=True, upload_to='combustible/candado_nuevo/%Y/%m/', verbose_name='Foto candado nuevo')),
                ('foto_ticket', models.ImageField(blank=True, null=True, upload_to='combustible/tickets/%Y/%m/', verbose_name='Foto del ticket o medidor')),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('EN_PROCESO', 'En proceso de carga'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='INICIADO', max_length=20, verbose_name='Estado de la carga')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas_combustible', to='unidades.unidad', verbose_name='Unidad')),
                ('despachador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargas', to='combustible.despachador', verbose_name='Despachador')),
            ],
            options={
                'verbose_name': 'Carga de Combustible',
                'verbose_name_plural': 'Cargas de Combustible',
                'ordering': ['-fecha_hora_inicio'],
                'indexes': [models.Index(fields=['unidad', '-fecha_hora_inicio'], name='combustible_unidad__b02c8c_idx'), models.Index(fields=['despachador', '-fecha_hora_inicio'], name='combustible_despach_b4d2d6_idx'), models.Index(fields=['estado', '-fecha_hora_inicio'], name='combustible_estado_113600_idx')],
            },
        ),
    ]
