# Generated by Django 5.2.7 on 2025-11-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargacombustible',
            name='nivel_combustible_inicial',
            field=models.CharField(choices=[('VACIO', 'Vacío'), ('CUARTO', '1/4'), ('MEDIO', '1/2'), ('TRES_CUARTOS', '3/4')], max_length=20, verbose_name='Nivel de combustible inicial'),
        ),
    ]
