# Generated by Django 5.2.7 on 2025-12-08 03:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('operadores', '0001_initial'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('prioridad_default', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoría de Falla',
                'verbose_name_plural': 'Categorías de Fallas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo')], max_length=20)),
                ('descripcion', models.TextField()),
                ('kilometraje_sugerido', models.IntegerField(blank=True, help_text='Kilometraje sugerido para este mantenimiento', null=True)),
                ('dias_sugeridos', models.IntegerField(blank=True, help_text='Días sugeridos entre mantenimientos', null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('descripcion_problema', models.TextField(help_text='Descripción del problema o servicio requerido')),
                ('sintomas', models.TextField(blank=True, help_text='Síntomas observados')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('fecha_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('kilometraje_ingreso', models.IntegerField(help_text='Kilometraje al ingresar al taller')),
                ('kilometraje_salida', models.IntegerField(blank=True, help_text='Kilometraje al salir del taller', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_DIAGNOSTICO', 'En Diagnóstico'), ('ESPERANDO_PIEZAS', 'Esperando Piezas'), ('EN_REPARACION', 'En Reparación'), ('EN_PRUEBAS', 'En Pruebas'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('diagnostico', models.TextField(blank=True, help_text='Diagnóstico técnico del problema')),
                ('fecha_diagnostico', models.DateTimeField(blank=True, null=True)),
                ('trabajo_realizado', models.TextField(blank=True, help_text='Descripción del trabajo realizado')),
                ('costo_estimado_mano_obra', models.DecimalField(decimal_places=2, default=0, help_text='Costo estimado de mano de obra', max_digits=10)),
                ('costo_real_mano_obra', models.DecimalField(decimal_places=2, default=0, help_text='Costo real de mano de obra', max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('categoria_falla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='taller.categoriafalla')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_taller_creadas', to=settings.AUTH_USER_MODEL)),
                ('mecanico_asignado', models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Mecánicos'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('operador_reporta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_reportadas', to='operadores.operador')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_supervisadas', to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_trabajo', to='unidades.unidad')),
                ('tipo_mantenimiento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='taller.tipomantenimiento')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_creacion'],
                'permissions': [('diagnosticar_orden', 'Puede realizar diagnóstico'), ('asignar_mecanico', 'Puede asignar mecánicos'), ('aprobar_orden', 'Puede aprobar órdenes'), ('cerrar_orden', 'Puede cerrar órdenes')],
            },
        ),
        migrations.CreateModel(
            name='PiezaRequerida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_uso', models.TextField(blank=True, help_text='Descripción de dónde/cómo se usará la pieza')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Solicitar'), ('SOLICITADA', 'Solicitada en Requisición'), ('EN_COMPRA', 'En Proceso de Compra'), ('RECIBIDA', 'Recibida en Almacén'), ('INSTALADA', 'Instalada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario estimado', max_digits=10)),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, help_text='Costo unitario real', max_digits=10, null=True)),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_instalacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_agregada', models.DateTimeField(auto_now_add=True)),
                ('agregada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas_taller_agregadas', to=settings.AUTH_USER_MODEL)),
                ('item_requisicion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_orden_trabajo', to='compras.itemrequisicion')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas_requeridas', to='taller.ordentrabajo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto')),
            ],
            options={
                'verbose_name': 'Pieza Requerida',
                'verbose_name_plural': 'Piezas Requeridas',
                'ordering': ['estado', 'fecha_agregada'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('estado_nuevo', models.CharField(max_length=20)),
                ('comentario', models.TextField(blank=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='taller/seguimientos/')),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='taller.ordentrabajo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Orden',
                'verbose_name_plural': 'Seguimientos de Órdenes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición')),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('tipo_mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='taller.tipomantenimiento')),
            ],
            options={
                'verbose_name': 'Item de Checklist',
                'verbose_name_plural': 'Items de Checklist',
                'ordering': ['tipo_mantenimiento', 'orden', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_servicio', models.DateField()),
                ('kilometraje_ingreso', models.IntegerField()),
                ('kilometraje_salida', models.IntegerField(blank=True, null=True)),
                ('tipo_servicio', models.CharField(max_length=200)),
                ('descripcion_breve', models.TextField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tiempo_fuera_servicio_dias', models.IntegerField(default=0)),
                ('tiempo_fuera_servicio_horas', models.DecimalField(decimal_places=1, default=0, help_text='Horas totales en taller', max_digits=6)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_mantenimiento', to='unidades.unidad')),
                ('orden_trabajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='taller.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Historial de Mantenimiento',
                'verbose_name_plural': 'Historiales de Mantenimiento',
                'ordering': ['-fecha_servicio'],
                'indexes': [models.Index(fields=['unidad', '-fecha_servicio'], name='taller_hist_unidad__4317ce_idx'), models.Index(fields=['unidad', '-kilometraje_ingreso'], name='taller_hist_unidad__c4dac9_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChecklistOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('OK', 'OK'), ('REQUIERE_ATENCION', 'Requiere Atención'), ('REPARADO', 'Reparado'), ('NO_APLICA', 'No Aplica')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('item_checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.checklistmantenimiento')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='taller.ordentrabajo')),
            ],
            options={
                'verbose_name': 'Checklist de Orden',
                'verbose_name_plural': 'Checklists de Órdenes',
                'unique_together': {('orden_trabajo', 'item_checklist')},
            },
        ),
    ]
