# Generated by Django 5.2.7 on 2026-02-27 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_asignaciondirectaalmacen'),
        ('compras', '0001_initial'),
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezarequerida',
            name='nombre_pieza',
            field=models.CharField(blank=True, help_text='Nombre libre cuando no existe en almacén', max_length=300, verbose_name='Nombre de la pieza'),
        ),
        migrations.AddField(
            model_name='piezarequerida',
            name='producto_almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_taller', to='almacen.productoalmacen', verbose_name='Producto en almacén'),
        ),
        migrations.AlterField(
            model_name='piezarequerida',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.producto'),
        ),
    ]
