# Generated by Django 5.2.7 on 2026-03-03 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_piezarequerida_nombre_pieza_and_more'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteFalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('operador_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre del operador')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del problema')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='taller/reportes/%Y/%m/', verbose_name='Foto del problema')),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_ATENCION', 'En Atención'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='NUEVO', max_length=15)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_taller', models.TextField(blank=True, verbose_name='Notas de taller')),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_falla_atendidos', to=settings.AUTH_USER_MODEL, verbose_name='Atendido por')),
                ('categoria_falla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='taller.categoriafalla', verbose_name='Categoría de falla')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reporte_origen', to='taller.ordentrabajo', verbose_name='Orden de trabajo generada')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_falla', to='unidades.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Reporte de Falla',
                'verbose_name_plural': 'Reportes de Falla',
                'ordering': ['-fecha_reporte'],
                'indexes': [models.Index(fields=['estado', '-fecha_reporte'], name='taller_repo_estado_8e577f_idx'), models.Index(fields=['unidad', '-fecha_reporte'], name='taller_repo_unidad__3b245d_idx')],
            },
        ),
    ]
