# Generated by Django 5.2.7 on 2026-03-04 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del reporte')),
                ('modulo', models.CharField(choices=[('ALMACEN', 'Almacén'), ('COMBUSTIBLE', 'Combustible'), ('TALLER', 'Taller')], max_length=20, verbose_name='Módulo')),
                ('tipo_reporte', models.CharField(choices=[('ALMACEN_INVENTARIO', 'Almacén — Inventario general'), ('ALMACEN_STOCK_CRITICO', 'Almacén — Stock crítico'), ('ALMACEN_CADUCIDAD', 'Almacén — Próximos a caducar'), ('ALMACEN_MOVIMIENTOS', 'Almacén — Movimientos del período'), ('COMBUSTIBLE_CARGAS', 'Combustible — Cargas del período'), ('COMBUSTIBLE_CONSUMO', 'Combustible — Consumo por unidad'), ('COMBUSTIBLE_ALERTAS', 'Combustible — Alertas de candado')], max_length=40, verbose_name='Tipo de reporte')),
                ('frecuencia', models.CharField(choices=[('DIARIO', 'Diario'), ('SEMANAL', 'Semanal'), ('MENSUAL', 'Mensual')], max_length=10, verbose_name='Frecuencia')),
                ('dia_semana', models.IntegerField(blank=True, choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], help_text='Solo para frecuencia semanal', null=True, verbose_name='Día de la semana')),
                ('dia_mes', models.IntegerField(blank=True, help_text='Solo para frecuencia mensual (1-28)', null=True, verbose_name='Día del mes')),
                ('destinatarios', models.TextField(help_text='Emails separados por coma. Ej: juan@empresa.com, maria@empresa.com', verbose_name='Destinatarios')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ultimo_envio', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Último envío')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_configurados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Configuración de Reporte',
                'verbose_name_plural': 'Configuraciones de Reportes',
                'ordering': ['modulo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('periodo_inicio', models.DateField(verbose_name='Período inicio')),
                ('periodo_fin', models.DateField(verbose_name='Período fin')),
                ('estado', models.CharField(choices=[('GENERADO', 'Generado y enviado'), ('ERROR', 'Error al generar'), ('PARCIAL', 'Enviado con errores parciales')], default='GENERADO', max_length=10)),
                ('destinatarios_enviados', models.TextField(blank=True, help_text='Emails que recibieron el reporte', verbose_name='Enviado a')),
                ('resumen', models.JSONField(default=dict, help_text='Snapshot de los datos clave del reporte', verbose_name='Resumen de datos')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Error')),
                ('configuracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_generados', to='reportes.configuracionreporte', verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Reporte Generado',
                'verbose_name_plural': 'Reportes Generados',
                'ordering': ['-fecha_generacion'],
                'indexes': [models.Index(fields=['configuracion', '-fecha_generacion'], name='reportes_re_configu_b9bba1_idx'), models.Index(fields=['-fecha_generacion'], name='reportes_re_fecha_g_a891ce_idx')],
            },
        ),
    ]
