# Generated by Django 5.2.7 on 2026-07-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0004_reportegenerado_narrativa_ia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionreporte',
            name='modulo',
            field=models.CharField(choices=[('ALMACEN', 'Almacén'), ('COMBUSTIBLE', 'Combustible'), ('TALLER', 'Taller'), ('UNIDADES', 'Unidades'), ('FLOTA', 'Flota (Dollys / Equipos / Cajas Secas)')], max_length=20, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='configuracionreporte',
            name='tipo_reporte',
            field=models.CharField(choices=[('ALMACEN_INVENTARIO', 'Almacén — Inventario general'), ('ALMACEN_STOCK_CRITICO', 'Almacén — Stock crítico'), ('ALMACEN_CADUCIDAD', 'Almacén — Próximos a caducar'), ('ALMACEN_MOVIMIENTOS', 'Almacén — Movimientos del período'), ('COMBUSTIBLE_CARGAS', 'Combustible — Cargas del período'), ('COMBUSTIBLE_CONSUMO', 'Combustible — Consumo por unidad'), ('COMBUSTIBLE_ALERTAS', 'Combustible — Alertas de candado'), ('UNIDADES_KILOMETRAJE', 'Unidades — Kilometraje de flota'), ('FLOTA_VIGENCIAS', 'Flota — Vigencias de dollys, equipos y cajas secas')], max_length=40, verbose_name='Tipo de reporte'),
        ),
    ]
