# Generated by Django 5.2.7 on 2026-08-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0009_alter_configuracionreporte_tipo_reporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionreporte',
            name='modulo',
            field=models.CharField(choices=[('ALMACEN', 'Almacén'), ('COMBUSTIBLE', 'Combustible'), ('TALLER', 'Taller'), ('UNIDADES', 'Unidades'), ('FLOTA', 'Flota (Dollys / Equipos / Cajas Secas)'), ('MODULACION', 'Modulación'), ('VACIOS', 'Vacíos')], max_length=20, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='configuracionreporte',
            name='tipo_reporte',
            field=models.CharField(choices=[('ALMACEN_INVENTARIO', 'Almacén — Inventario general'), ('ALMACEN_STOCK_CRITICO', 'Almacén — Stock crítico'), ('ALMACEN_CADUCIDAD', 'Almacén — Próximos a caducar'), ('ALMACEN_MOVIMIENTOS', 'Almacén — Movimientos del período'), ('ALMACEN_ANALISIS_INTEGRAL', 'Almacén — Análisis integral (asignaciones, entradas, auditoría)'), ('COMBUSTIBLE_CARGAS', 'Combustible — Cargas del período'), ('COMBUSTIBLE_CONSUMO', 'Combustible — Consumo por unidad'), ('COMBUSTIBLE_ALERTAS', 'Combustible — Alertas de candado'), ('UNIDADES_KILOMETRAJE', 'Unidades — Kilometraje de flota'), ('UNIDADES_BALANZA_UTILIDAD', 'Unidades — Balanza de utilidad/pérdida por unidad'), ('FLOTA_VIGENCIAS', 'Flota — Vigencias de dollys, equipos y cajas secas'), ('MODULACION_CONTENEDORES_OPERADOR', 'Modulación — Contenedores extraídos por operador'), ('MODULACION_RETIROS_PATIO', 'Modulación — Retiros de Patio Esperanza'), ('VACIOS_ENTREGAS_SEMANAL', 'Vacíos — Entregas por operador (semanal)'), ('VACIOS_RETRASOS', 'Vacíos — Retrasos del período')], max_length=40, verbose_name='Tipo de reporte'),
        ),
    ]
