# Generated by Django 5.2.7 on 2026-08-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecepcionPipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de recepción')),
                ('litros', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Litros recibidos')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo total pagado')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('factura', models.FileField(blank=True, null=True, upload_to='combustible/pipas/%Y/%m/', verbose_name='Factura/ticket')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recepción de Pipa',
                'verbose_name_plural': 'Recepciones de Pipa',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TarifaKilometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por km')),
                ('vigente_desde', models.DateField(verbose_name='Vigente desde')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tarifa por Kilómetro',
                'verbose_name_plural': 'Tarifas por Kilómetro',
                'ordering': ['-vigente_desde'],
            },
        ),
        migrations.CreateModel(
            name='PrecioDieselMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mes')),
                ('litros_totales', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Litros totales')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Costo total')),
                ('precio_promedio_litro', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Precio promedio por litro')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio de Diésel Mensual',
                'verbose_name_plural': 'Precios de Diésel Mensuales',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('anio', 'mes')},
            },
        ),
    ]
