"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_template_maths',
    'django_apscheduler',
    'config',
    # Apps del proyecto
    'modulos.operadores',
    'modulos.unidades',
    'modulos.bitacoras',
    'modulos.combustible',
    'modulos.compras',
    'modulos.taller',
    'modulos.almacen',
    'modulos.reportes',
    'modulos.equipos',
    'modulos.dollys',
    'modulos.caja_seca',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# Google APIs
GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY', '')
GOOGLE_VISION_API_KEY = os.environ.get('GOOGLE_VISION_API_KEY', '')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'config.context_processors.alertas_combustible',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default':env.db('DBURL')
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
# Idioma y zona horaria
LANGUAGE_CODE = 'es-mx'
TIME_ZONE = 'America/Mexico_City'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [Path.joinpath(BASE_DIR, 'static'), ]

# Media files storage - DigitalOcean Spaces
# Check if Spaces credentials are available
SPACES_KEY = env.str('SPACES_KEY', default='')
SPACES_SECRET = env.str('SPACES_SECRET', default='')
SPACES_BUCKET = env.str('SPACES_BUCKET', default='')

# Only use Spaces if credentials are configured
USE_SPACES = bool(SPACES_KEY and SPACES_SECRET and SPACES_BUCKET)

if USE_SPACES:
    # DigitalOcean Spaces settings
    AWS_ACCESS_KEY_ID = SPACES_KEY
    AWS_SECRET_ACCESS_KEY = SPACES_SECRET
    AWS_STORAGE_BUCKET_NAME = SPACES_BUCKET
    AWS_S3_ENDPOINT_URL = env.str('SPACES_ENDPOINT', default='https://sfo3.digitaloceanspaces.com')
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_LOCATION = 'media'
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = True
    AWS_QUERYSTRING_EXPIRE = 3600  # URLs válidas por 1 hora

    # Media files configuration
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/{AWS_LOCATION}/'

    print(f"Using Spaces: {AWS_STORAGE_BUCKET_NAME} at {MEDIA_URL}")
else:
    # Local storage (fallback)
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    print("Using local media storage (Spaces credentials not configured)")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuración de email (ejemplo con Gmail)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'apikey'  # Cambiar
EMAIL_HOST_PASSWORD = env.str('EMAIL_HOST_PASSWORD')  # Usar App Password de Gmail
DEFAULT_FROM_EMAIL = 'bitacora@transporteskasu.com.mx'

# ---------------------------------------------------------------------------
# IAKasu — Configuración de Inteligencia Artificial
# ---------------------------------------------------------------------------
ANTHROPIC_API_KEY = env.str('ANTHROPIC_API_KEY', default='')

# Toggle global: False desactiva todas las llamadas a Claude API
IA_HABILITADA = env.bool('IA_HABILITADA', default=True)

# Score mínimo para invocar Claude API en análisis de combustible
# Solo se llama cuando la anomalía es ALTO o CRITICO (evita costos en BAJO/MEDIO)
IA_SCORE_MINIMO_CLAUDE = env.str('IA_SCORE_MINIMO_CLAUDE', default='ALTO')

# Destinatarios de alertas IA de combustible (score ALTO / CRITICO)
IA_ALERTAS_COMBUSTIBLE_EMAILS = env.list(
    'IA_ALERTAS_COMBUSTIBLE_EMAILS',
    default=[
        'gerencia.general@transporteskasu.com.mx',
        'f.suarez@loginco.com.mx',
        'administracion@transporteskasu.com.mx',
        'xoyocl2@gmail.com',
    ]
)

# ---------------------------------------------------------------------------
# OpenWA — WhatsApp Business API
# ---------------------------------------------------------------------------
WA_API_URL = env.str('WA_API_URL', default='')
WA_API_KEY = env.str('WA_API_KEY', default='')
WA_SESSION_ID = env.str('WA_SESSION_ID', default='')
WA_ADMIN_CHAT = env.str('WA_ADMIN_CHAT', default='')
WA_WEBHOOK_SECRET = env.str('WA_WEBHOOK_SECRET', default='')
WA_ALLOWED_NUMBERS = env.list('WA_ALLOWED_NUMBERS', default=[])
WA_REPORTES_ENABLED = env.bool('WA_REPORTES_ENABLED', default=True)

# Twilio — WhatsApp templates y notificaciones a clientes
TWILIO_ACCOUNT_SID = env.str('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = env.str('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM = env.str('TWILIO_WHATSAPP_FROM', default='')
TWILIO_CONTENT_SID_BITACORA = env.str('TWILIO_CONTENT_SID_BITACORA', default='')

# Destinatarios de notificaciones de autorización de salidas de almacén.
# Se puede sobreescribir vía .env: ALMACEN_AUTORIZACION_EMAILS=correo1@x.com,correo2@x.com
ALMACEN_AUTORIZACION_EMAILS = env.list(
    'ALMACEN_AUTORIZACION_EMAILS',
    default=[
        'gerencia.general@transporteskasu.com.mx',
        'administracion@transporteskasu.com.mx',
        'xoyocl2@gmail.com',
    ]
)

# Celery deshabilitado. Los reportes periódicos se ejecutan vía GitHub Actions.
# CELERY_BROKER_URL = ''
# CELERY_RESULT_BACKEND = ''

# Seguridad
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['https://*.ondigitalocean.app'])

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Autenticación
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'inicio'
LOGOUT_REDIRECT_URL = 'login'

# ─── Reportes automáticos ───────────────────────────────────────────────────
# La configuración de reportes vive en la BD (ConfiguracionReporte).
# El scheduler revisa reportes pendientes diariamente a las 07:00 MX.
# Para cambiar la hora de revisión, definir REPORTES_HORA_REVISION en .env
REPORTES_HORA_REVISION = env.str('REPORTES_HORA_REVISION', default='07:00')