# Generated by Django 5.2.7 on 2026-08-17 21:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bitacoras', '0009_bitacoraviaje_cliente_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TerminalPortuaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True, verbose_name='Nombre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Terminal portuaria',
                'verbose_name_plural': 'Terminales portuarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Modulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('tipo_contenedor', models.CharField(help_text='Ej. 20DC, 40HC (tal como llega del sistema de origen)', max_length=10, verbose_name='Tipo de contenedor')),
                ('peso_toneladas', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peso (toneladas)')),
                ('contenedor', models.CharField(max_length=50, verbose_name='Contenedor')),
                ('num_pedimento', models.CharField(blank=True, max_length=30, verbose_name='Número de pedimento')),
                ('num_doda', models.CharField(blank=True, max_length=34, verbose_name='Número de DODA')),
                ('origen', models.CharField(choices=[('HAL9MIL', 'HAL9MIL / LOGINCO'), ('MANUAL', 'Captura manual')], default='MANUAL', max_length=10, verbose_name='Origen')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de modulación'), ('MODULADO', 'Modulado'), ('EN_PATIO_ESPERANZA', 'En Patio Esperanza'), ('ENVIADO_BITACORA', 'Enviado a Bitácora de Viajes'), ('RETIRADO_TERCERO', 'Retirado por transporte externo')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('transportista_externo', models.CharField(blank=True, max_length=120, verbose_name='Transportista externo')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de recepción')),
                ('fecha_retiro', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modulaciones', to='modulacion.agencia', verbose_name='Agencia')),
                ('bitacora_viaje', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulacion', to='bitacoras.bitacoraviaje', verbose_name='Bitácora de viaje')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulaciones', to='bitacoras.cliente', verbose_name='Cliente')),
                ('terminal_portuaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modulaciones', to='modulacion.terminalportuaria', verbose_name='Terminal portuaria')),
            ],
            options={
                'verbose_name': 'Modulación',
                'verbose_name_plural': 'Modulaciones',
                'ordering': ['-fecha_recepcion'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('num_doda__gt', '')), fields=('num_doda', 'contenedor'), name='uniq_doda_contenedor')],
            },
        ),
    ]
