# Generated by Django 5.2.7 on 2026-08-19 23:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulacion',
            name='fecha_recepcion',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha real del DODA cuando el origen la manda (HAL9MIL); si no llega, la fecha en que se recibió el registro.', verbose_name='Fecha de recepción'),
        ),
    ]
