# Generated by Django 5.2.7 on 2026-08-27 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulacion', '0002_alter_modulacion_fecha_recepcion'),
        ('operadores', '0001_initial'),
        ('unidades', '0002_unidad_control_combustible_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulacion',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, help_text='Se sella la primera vez que se asigna unidad y operador.', null=True, verbose_name='Fecha de asignación'),
        ),
        migrations.AddField(
            model_name='modulacion',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulaciones', to='operadores.operador', verbose_name='Operador asignado'),
        ),
        migrations.AddField(
            model_name='modulacion',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modulaciones', to='unidades.unidad', verbose_name='Unidad asignada'),
        ),
    ]
