# Generated by Django 5.2.7 on 2026-08-27 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulacion', '0003_modulacion_fecha_asignacion_modulacion_operador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulacion',
            name='fecha_patio_esperanza',
            field=models.DateTimeField(blank=True, help_text='Se sella la primera vez que el contenedor se manda a Patio Esperanza.', null=True, verbose_name='Fecha de entrada a Patio Esperanza'),
        ),
    ]
