# Generated by Django 5.2.7 on 2026-08-29 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulacion', '0004_modulacion_fecha_patio_esperanza'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencia',
            name='email_contacto',
            field=models.EmailField(blank=True, help_text='Destino de los avisos automáticos de retraso de vacíos.', max_length=254, verbose_name='Correo de contacto'),
        ),
    ]
