# Generated by Django 5.2.7 on 2026-09-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulacion', '0005_agencia_email_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulacion',
            name='carril',
            field=models.CharField(blank=True, max_length=10, verbose_name='Carril'),
        ),
        migrations.AddField(
            model_name='modulacion',
            name='fecha_modulacion_aduana',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de modulación ante aduana'),
        ),
        migrations.AddField(
            model_name='modulacion',
            name='hora_carga',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de carga'),
        ),
        migrations.AddField(
            model_name='modulacion',
            name='hora_ingreso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de ingreso'),
        ),
        migrations.AddField(
            model_name='modulacion',
            name='hora_registro',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de registro'),
        ),
        migrations.AddField(
            model_name='terminalportuaria',
            name='requiere_carril',
            field=models.BooleanField(default=False, verbose_name='Requiere carril'),
        ),
        migrations.AddField(
            model_name='terminalportuaria',
            name='requiere_datos_extra',
            field=models.BooleanField(default=False, help_text='Si está activo, el correo de HAL9MIL incluye un link para que el capturista complete carril/horarios de este contenedor.', verbose_name='Requiere datos de terminal'),
        ),
        migrations.AddField(
            model_name='terminalportuaria',
            name='requiere_hora_carga',
            field=models.BooleanField(default=False, verbose_name='Requiere hora de carga'),
        ),
        migrations.AddField(
            model_name='terminalportuaria',
            name='requiere_hora_ingreso',
            field=models.BooleanField(default=False, verbose_name='Requiere hora de ingreso'),
        ),
    ]
