# Generated by Django 5.2.7 on 2026-09-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulacion', '0006_modulacion_carril_modulacion_fecha_modulacion_aduana_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionProgramacionLCTPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph_message_id', models.CharField(max_length=255, unique=True, verbose_name='ID de mensaje (Graph)')),
                ('asunto', models.CharField(max_length=300, verbose_name='Asunto')),
                ('fecha_recibido', models.DateTimeField(verbose_name='Fecha de recepción del correo')),
                ('fecha_modulacion_aduana', models.DateField(blank=True, null=True, verbose_name='Fecha de modulación ante aduana')),
                ('estado', models.CharField(choices=[('OK', 'Procesado sin avisos'), ('OK_CON_AVISOS', 'Procesado con avisos'), ('ERROR', 'Error al procesar')], max_length=15, verbose_name='Estado')),
                ('total_renglones', models.PositiveIntegerField(default=0, verbose_name='Renglones en el Excel')),
                ('creadas', models.PositiveIntegerField(default=0, verbose_name='Modulaciones creadas')),
                ('actualizadas', models.PositiveIntegerField(default=0, verbose_name='Modulaciones actualizadas')),
                ('ambiguas', models.PositiveIntegerField(default=0, verbose_name='Coincidencias ambiguas')),
                ('detalle', models.JSONField(blank=True, default=list, help_text='[{contenedor, folio_lctpc, resultado, modulacion_id, tipo_cita}]', verbose_name='Detalle por contenedor')),
                ('mensaje_error', models.TextField(blank=True, verbose_name='Error / avisos')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Importación de programación LCTPC',
                'verbose_name_plural': 'Importaciones de programación LCTPC',
                'ordering': ['-fecha_recibido'],
            },
        ),
        migrations.AddField(
            model_name='modulacion',
            name='grupo_cita',
            field=models.CharField(blank=True, db_index=True, help_text='Comparten valor los 2 contenedores de un mismo FULL.', max_length=32, verbose_name='Grupo de cita FULL'),
        ),
        migrations.AddField(
            model_name='modulacion',
            name='tipo_cita',
            field=models.CharField(blank=True, choices=[('FULL', 'Full'), ('SENCILLO', 'Sencillo')], help_text='Clasificación FULL/SENCILLO derivada de la programación de la terminal.', max_length=10, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='modulacion',
            name='origen',
            field=models.CharField(choices=[('HAL9MIL', 'HAL9MIL / LOGINCO'), ('MANUAL', 'Captura manual'), ('LCTPC', 'Programación LCTPC')], default='MANUAL', max_length=10, verbose_name='Origen'),
        ),
    ]
