# Generated by Django 5.2.7 on 2026-09-10 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulacion', '0007_importacion_lctpc'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de modulación'), ('MODULADO', 'Modulado'), ('ASIGNADO', 'Asignado / pendiente de ingreso'), ('INGRESADO', 'Ingresado'), ('DESADUANAMIENTO_LIBRE', 'Desaduanamiento libre (verde)'), ('RECONOCIMIENTO_ADUANAL', 'Reconocimiento aduanal (rojo)'), ('RETENIDO', 'Retenido (esperando aduana)'), ('VERIFICACION_EN_TRANSPORTE', 'Verificación en transporte'), ('EN_PATIO_ESPERANZA', 'En Patio Esperanza'), ('ENVIADO_BITACORA', 'Enviado a Bitácora de Viajes'), ('RETIRADO_TERCERO', 'Retirado por transporte externo')], default='PENDIENTE', max_length=30, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='SeguimientoModulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de modulación'), ('MODULADO', 'Modulado'), ('ASIGNADO', 'Asignado / pendiente de ingreso'), ('INGRESADO', 'Ingresado'), ('DESADUANAMIENTO_LIBRE', 'Desaduanamiento libre (verde)'), ('RECONOCIMIENTO_ADUANAL', 'Reconocimiento aduanal (rojo)'), ('RETENIDO', 'Retenido (esperando aduana)'), ('VERIFICACION_EN_TRANSPORTE', 'Verificación en transporte'), ('EN_PATIO_ESPERANZA', 'En Patio Esperanza'), ('ENVIADO_BITACORA', 'Enviado a Bitácora de Viajes'), ('RETIRADO_TERCERO', 'Retirado por transporte externo')], max_length=30, verbose_name='Estado')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='modulacion.modulacion', verbose_name='Modulación')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Seguimiento de modulación',
                'verbose_name_plural': 'Seguimientos de modulación',
                'ordering': ['creado_en'],
            },
        ),
    ]
