# Generated by Django 5.2.7 on 2026-09-10 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulacion', '0008_estados_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulacion',
            name='sello_colocado',
            field=models.BooleanField(default=False, help_text='El contenedor sale con sello/candado colocado.', verbose_name='Sello colocado'),
        ),
        migrations.AddField(
            model_name='terminalportuaria',
            name='nombre_corto',
            field=models.CharField(blank=True, help_text='Etiqueta corta para reportes (ej. LCTPC, HUTCHINSON, APM).', max_length=30, verbose_name='Nombre corto'),
        ),
    ]
