# Generated by Django 5.2.7 on 2025-10-28 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre completo')),
                ('tipo', models.CharField(choices=[('LOCAL', 'Local'), ('FORANEO', 'Foráneo'), ('ESPERANZA', 'Foráneo Esperanza')], max_length=20, verbose_name='Tipo de operador')),
                ('licencia', models.CharField(blank=True, max_length=20, verbose_name='Número de licencia')),
                ('telefono', models.CharField(blank=True, max_length=15, verbose_name='Teléfono de contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('activo', models.BooleanField(default=True, verbose_name='Operador activo')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unidad_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='unidades.unidad', verbose_name='Unidad asignada')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['tipo', 'activo'], name='operadores__tipo_d27384_idx'), models.Index(fields=['nombre'], name='operadores__nombre_2d795f_idx')],
            },
        ),
    ]
