# Generated by Django 5.2.7 on 2025-10-28 05:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operadores', '0001_initial'),
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad', models.CharField(choices=[('SENCILLO', 'Sencillo'), ('FULL', 'Full')], max_length=20, verbose_name='Modalidad')),
                ('contenedor', models.CharField(blank=True, max_length=50, verbose_name='Número de contenedor')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peso (kg)')),
                ('fecha_carga', models.DateTimeField(verbose_name='Fecha/hora de carga')),
                ('fecha_salida', models.DateTimeField(verbose_name='Fecha/hora de salida')),
                ('fecha_llegada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de llegada')),
                ('diesel_cargado', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Diesel cargado (litros)')),
                ('kilometraje_salida', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilometraje de salida')),
                ('kilometraje_llegada', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilometraje de llegada')),
                ('cp_origen', models.CharField(default='40812', max_length=10, verbose_name='Código postal origen')),
                ('cp_destino', models.CharField(blank=True, max_length=10, verbose_name='Código postal destino')),
                ('destino', models.TextField(verbose_name='Destino (descripción)')),
                ('distancia_calculada', models.DecimalField(blank=True, decimal_places=2, help_text='Distancia en kilómetros según Google Maps', max_digits=10, null=True, verbose_name='Distancia calculada (km)')),
                ('duracion_estimada', models.IntegerField(blank=True, help_text='Duración estimada en minutos según Google Maps', null=True, verbose_name='Duración estimada (min)')),
                ('sellos', models.CharField(blank=True, max_length=100, verbose_name='Números de sellos')),
                ('reparto', models.BooleanField(default=False, verbose_name='Viaje con reparto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('completado', models.BooleanField(default=False, verbose_name='Viaje completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='operadores.operador', verbose_name='Operador')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bitacoras', to='unidades.unidad', verbose_name='Unidad')),
            ],
            options={
                'verbose_name': 'Bitácora de viaje',
                'verbose_name_plural': 'Bitácoras de viajes',
                'ordering': ['-fecha_salida'],
                'indexes': [models.Index(fields=['-fecha_salida'], name='bitacoras_b_fecha_s_69a0e7_idx'), models.Index(fields=['operador', 'fecha_salida'], name='bitacoras_b_operado_fb0d78_idx'), models.Index(fields=['unidad', 'fecha_salida'], name='bitacoras_b_unidad__67d7ef_idx'), models.Index(fields=['completado'], name='bitacoras_b_complet_4fd154_idx')],
            },
        ),
    ]
