# Generated by Django 5.2.7 on 2025-10-28 05:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=10, unique=True, verbose_name='Número económico')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa vehicular')),
                ('tipo', models.CharField(choices=[('LOCAL', 'Local'), ('FORANEA', 'Foránea'), ('ESPERANZA', 'Esperanza')], max_length=20, verbose_name='Tipo de unidad')),
                ('marca', models.CharField(blank=True, max_length=50, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo')),
                ('año', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2030)], verbose_name='Año')),
                ('capacidad_combustible', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Capacidad de combustible (litros)')),
                ('rendimiento_esperado', models.DecimalField(decimal_places=2, help_text='Rendimiento esperado en km/litro', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Rendimiento esperado (km/lt)')),
                ('kilometraje_actual', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilometraje actual')),
                ('activa', models.BooleanField(default=True, verbose_name='Unidad activa')),
                ('fecha_alta', models.DateField(auto_now_add=True, verbose_name='Fecha de alta')),
                ('fecha_baja', models.DateField(blank=True, null=True, verbose_name='Fecha de baja')),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Último mantenimiento')),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
                'ordering': ['numero_economico'],
                'indexes': [models.Index(fields=['tipo', 'activa'], name='unidades_un_tipo_a25a64_idx'), models.Index(fields=['numero_economico'], name='unidades_un_numero__ac0720_idx')],
            },
        ),
    ]
