# Generated by Django 5.2.7 on 2026-03-24 22:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraviaje',
            name='contenedor_2',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contenedor 2'),
        ),
        migrations.AddField(
            model_name='bitacoraviaje',
            name='peso_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peso 2 (kg)'),
        ),
        migrations.AddField(
            model_name='bitacoraviaje',
            name='salida_a_ruta',
            field=models.CharField(blank=True, max_length=50, verbose_name='Salida a ruta'),
        ),
        migrations.AddField(
            model_name='bitacoraviaje',
            name='sellos_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sellos contenedor 2'),
        ),
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='contenedor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Contenedor 1'),
        ),
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='modalidad',
            field=models.CharField(choices=[('SENCILLO', 'Sencillo'), ('FULL', 'Full'), ('LOCAL', 'Local')], max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peso 1 (kg)'),
        ),
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='sellos',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sellos contenedor 1'),
        ),
    ]
