# Generated by Django 5.2.7 on 2026-03-24 23:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0002_campos_full_y_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='diesel_cargado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Diesel cargado (litros)'),
        ),
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='kilometraje_salida',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Kilometraje de salida'),
        ),
    ]
