# Generated by Django 5.2.7 on 2026-03-25 20:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0003_diesel_km_opcionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraviaje',
            name='cp_destino_2',
            field=models.CharField(blank=True, max_length=10, verbose_name='CP destino 2 (reparto)'),
        ),
        migrations.AddField(
            model_name='bitacoraviaje',
            name='distancia_calculada_2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distancia al segundo destino (reparto) en km según Google Maps', max_digits=10, null=True, verbose_name='Distancia calculada destino 2 (km)'),
        ),
        migrations.AddField(
            model_name='bitacoraviaje',
            name='duracion_estimada_2',
            field=models.IntegerField(blank=True, help_text='Duración estimada al segundo destino en minutos', null=True, verbose_name='Duración estimada destino 2 (min)'),
        ),
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='modalidad',
            field=models.CharField(choices=[('SENCILLO', 'Sencillo'), ('FULL', 'Full'), ('LOCAL', 'Local'), ('LOCAL_FULL', 'Local Full')], max_length=20, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peso 1 (toneladas)'),
        ),
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='peso_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Peso 2 (toneladas)'),
        ),
    ]
