# Generated by Django 5.2.7 on 2026-06-22 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0004_bitacoraviaje_cp_destino_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('celular', models.CharField(blank=True, help_text='Con código de país, ej. +5217531234567', max_length=20, verbose_name='Celular (WhatsApp)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='bitacoraviaje',
            name='tipo_contenedor',
            field=models.CharField(choices=[('20', '20 pies'), ('40', '40 pies')], default='40', max_length=2, verbose_name='Tipo de contenedor'),
        ),
        migrations.AddField(
            model_name='bitacoraviaje',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras', to='bitacoras.cliente', verbose_name='Cliente'),
        ),
    ]
