# Generated by Django 5.2.7 on 2026-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0005_cliente_bitacoraviaje_tipo_contenedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraviaje',
            name='domicilio_carta_porte',
            field=models.TextField(blank=True, verbose_name='Domicilio carta porte'),
        ),
        migrations.AlterField(
            model_name='bitacoraviaje',
            name='destino',
            field=models.TextField(verbose_name='Dirección de entrega'),
        ),
    ]
