# Generated by Django 5.2.7 on 2026-08-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0006_add_domicilio_carta_porte'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraviaje',
            name='ingreso_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='distancia_efectiva × tarifa por km vigente al completar el viaje', max_digits=10, null=True, verbose_name='Ingreso calculado'),
        ),
    ]
