# Generated by Django 5.2.7 on 2026-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0007_bitacoraviaje_ingreso_calculado'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraviaje',
            name='fecha_hora_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de entrega'),
        ),
    ]
