# Generated by Django 5.2.7 on 2026-08-17 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0008_bitacoraviaje_fecha_hora_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoraviaje',
            name='cliente_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_contenedor_2', to='bitacoras.cliente', verbose_name='Cliente (contenedor 2)'),
        ),
        migrations.AddField(
            model_name='bitacoraviaje',
            name='fecha_hora_entrega_2',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de entrega (contenedor 2)'),
        ),
    ]
