# Generated by Django 5.2.7 on 2026-09-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitacoras', '0009_bitacoraviaje_cliente_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='alias',
            field=models.CharField(blank=True, help_text='Código corto para agrupar viajes y modulaciones en reportes.', max_length=20, verbose_name='Alias'),
        ),
    ]
