# Generated by Django 5.2.7 on 2025-12-05 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRequisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion_adicional', models.TextField(blank=True, help_text='Especificaciones adicionales')),
            ],
            options={
                'verbose_name': 'Item de Requisición',
                'verbose_name_plural': 'Items de Requisición',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('unidad_medida', models.CharField(help_text='Ej: Pieza, Litro, Kg, Caja', max_length=50)),
                ('categoria', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('contacto', models.CharField(help_text='Nombre del contacto principal', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('ENVIADA', 'Enviada al Proveedor'), ('CONFIRMADA', 'Confirmada por Proveedor'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDA', 'Recibida en Almacén'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('factura_numero', models.CharField(blank=True, max_length=50)),
                ('factura_fecha', models.DateField(blank=True, null=True)),
                ('factura_monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('factura_archivo', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('notas', models.TextField(blank=True)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item_requisicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.itemrequisicion')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.ordencompra')),
            ],
            options={
                'verbose_name': 'Item de Orden de Compra',
                'verbose_name_plural': 'Items de Orden de Compra',
            },
        ),
        migrations.AddField(
            model_name='itemrequisicion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.producto'),
        ),
        migrations.CreateModel(
            name='RecepcionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ALMACENADO', 'Almacenado'), ('DISTRIBUIDO', 'Distribuido')], default='RECIBIDO', max_length=20)),
                ('ubicacion_almacen', models.CharField(help_text='Ubicación física en almacén', max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('remision', models.CharField(blank=True, help_text='Número de remisión', max_length=50)),
                ('foto_recepcion', models.ImageField(blank=True, null=True, upload_to='recepciones/')),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='compras.ordencompra')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de Almacén',
                'verbose_name_plural': 'Recepciones de Almacén',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='ItemRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_aceptada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_rechazada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('item_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.itemordencompra')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.recepcionalmacen')),
            ],
            options={
                'verbose_name': 'Item de Recepción',
                'verbose_name_plural': 'Items de Recepción',
            },
        ),
        migrations.CreateModel(
            name='Requisicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_requerida', models.DateField(help_text='Fecha en que se necesitan los productos')),
                ('justificacion', models.TextField(help_text='Motivo de la requisición')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EN_COMPRA', 'En Proceso de Compra'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_aprobacion', models.TextField(blank=True)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisiciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisiciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requisición',
                'verbose_name_plural': 'Requisiciones',
                'ordering': ['-fecha_solicitud'],
                'permissions': [('aprobar_requisicion', 'Puede aprobar requisiciones'), ('procesar_compra', 'Puede procesar compras'), ('gestionar_almacen', 'Puede gestionar almacén')],
            },
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='requisicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='compras.requisicion'),
        ),
        migrations.AddField(
            model_name='itemrequisicion',
            name='requisicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compras.requisicion'),
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='compras.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
                'unique_together': {('producto', 'ubicacion')},
            },
        ),
    ]
