# Generated by Django 5.2.7 on 2026-05-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=30, unique=True, verbose_name='Número económico')),
                ('tipo', models.CharField(choices=[('CHASIS', 'Chasis'), ('PLANA', 'Plana'), ('OTRO', 'Otro')], default='CHASIS', max_length=10, verbose_name='Tipo')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('placas', models.CharField(blank=True, max_length=20, verbose_name='Placas')),
                ('marca', models.CharField(blank=True, max_length=60, verbose_name='Marca')),
                ('modelo', models.CharField(blank=True, max_length=60, verbose_name='Modelo')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('numero_serie', models.CharField(max_length=60, unique=True, verbose_name='No. de serie')),
                ('vigencia_doble_articulado', models.DateField(blank=True, null=True, verbose_name='Vigencia doble articulado')),
                ('verificacion', models.BooleanField(default=True, verbose_name='Verificación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['numero_economico'],
                'indexes': [models.Index(fields=['slug'], name='equipos_equ_slug_4bfd6e_idx'), models.Index(fields=['tipo', 'activo'], name='equipos_equ_tipo_a6afed_idx'), models.Index(fields=['marca'], name='equipos_equ_marca_1f7103_idx')],
            },
        ),
    ]
