# Generated by Django 5.2.7 on 2026-05-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dolly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_economico', models.CharField(max_length=30, unique=True, verbose_name='Número económico')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('marca', models.CharField(blank=True, max_length=60, verbose_name='Marca')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('numero_serie', models.CharField(max_length=60, unique=True, verbose_name='No. de serie')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dolly',
                'verbose_name_plural': 'Dollys',
                'ordering': ['numero_economico'],
                'indexes': [models.Index(fields=['slug'], name='dollys_doll_slug_e1b2d9_idx'), models.Index(fields=['activo'], name='dollys_doll_activo_91b306_idx'), models.Index(fields=['marca'], name='dollys_doll_marca_5a7d5c_idx')],
            },
        ),
    ]
