# Generated by Django 5.2.7 on 2025-11-30 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0002_alter_cargacombustible_nivel_combustible_inicial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despachador',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despachador', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
