# Generated by Django 5.2.7 on 2025-12-04 23:18

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0003_despachador_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargacombustible',
            name='foto_candado_anterior',
            field=models.ImageField(storage=config.storage_backends.MediaStorage(), upload_to='combustible/candado_anterior/%Y/%m/', verbose_name='Foto candado anterior'),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='foto_candado_nuevo',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.MediaStorage(), upload_to='combustible/candado_nuevo/%Y/%m/', verbose_name='Foto candado nuevo'),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='foto_numero_economico',
            field=models.ImageField(storage=config.storage_backends.MediaStorage(), upload_to='combustible/numero_economico/%Y/%m/', verbose_name='Foto número económico'),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='foto_tablero',
            field=models.ImageField(storage=config.storage_backends.MediaStorage(), upload_to='combustible/tablero/%Y/%m/', verbose_name='Foto del tablero'),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='foto_ticket',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.MediaStorage(), upload_to='combustible/tickets/%Y/%m/', verbose_name='Foto del ticket o medidor'),
        ),
    ]
