# Generated by Django 5.1.2 on 2026-02-04 22:57

import config.storage_backends
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0004_alter_cargacombustible_foto_candado_anterior_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoCandadoNuevo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(storage=config.storage_backends.MediaStorage(), upload_to='combustible/candado_nuevo/%Y/%m/', verbose_name='Foto del candado nuevo')),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Tanque 1, Tanque 2', max_length=100, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_candado_nuevo', to='combustible.cargacombustible', verbose_name='Carga de combustible')),
            ],
            options={
                'verbose_name': 'Foto de Candado Nuevo',
                'verbose_name_plural': 'Fotos de Candado Nuevo',
                'ordering': ['created_at'],
            },
        ),
    ]
