# Generated by Django 5.2.8 on 2026-02-19 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0005_fotocandadonuevo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaCombustible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('CANDADO_ALTERADO', 'Candado Alterado'), ('CANDADO_VIOLADO', 'Candado Violado'), ('SIN_CANDADO', 'Sin Candado'), ('EXCESO_COMBUSTIBLE', 'Exceso de Combustible')], max_length=30, verbose_name='Tipo de alerta')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de generación')),
                ('resuelta', models.BooleanField(default=False, verbose_name='Resuelta')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='combustible.cargacombustible', verbose_name='Carga de combustible')),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_combustible_resueltas', to=settings.AUTH_USER_MODEL, verbose_name='Resuelta por')),
            ],
            options={
                'verbose_name': 'Alerta de Combustible',
                'verbose_name_plural': 'Alertas de Combustible',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
