# Generated by Django 5.2.7 on 2026-03-06 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0006_alertacombustible'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='numero_candado_anterior',
            field=models.CharField(blank=True, help_text='Extraído automáticamente por OCR de la foto del candado anterior', max_length=50, verbose_name='Número de candado anterior'),
        ),
        migrations.AddField(
            model_name='cargacombustible',
            name='ocr_candado_anterior_ok',
            field=models.BooleanField(default=False, verbose_name='OCR candado anterior procesado'),
        ),
        migrations.AddField(
            model_name='fotocandadonuevo',
            name='numero_candado',
            field=models.CharField(blank=True, help_text='Extraído automáticamente por OCR de la foto', max_length=50, verbose_name='Número de candado'),
        ),
        migrations.AddField(
            model_name='fotocandadonuevo',
            name='ocr_procesado',
            field=models.BooleanField(default=False, verbose_name='OCR procesado'),
        ),
        migrations.AlterField(
            model_name='alertacombustible',
            name='tipo_alerta',
            field=models.CharField(choices=[('CANDADO_ALTERADO', 'Candado Alterado'), ('CANDADO_VIOLADO', 'Candado Violado'), ('SIN_CANDADO', 'Sin Candado'), ('EXCESO_COMBUSTIBLE', 'Exceso de Combustible'), ('CANDADO_NO_COINCIDE', 'Candado no coincide con carga anterior')], max_length=30, verbose_name='Tipo de alerta'),
        ),
    ]
