# Generated by Django 5.2.7 on 2026-03-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0007_ocr_campos_candado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertacombustible',
            name='tipo_alerta',
            field=models.CharField(choices=[('CANDADO_ALTERADO', 'Candado Alterado'), ('CANDADO_VIOLADO', 'Candado Violado'), ('SIN_CANDADO', 'Sin Candado'), ('EXCESO_COMBUSTIBLE', 'Exceso de Combustible'), ('CANDADO_NO_COINCIDE', 'Candado no coincide con carga anterior'), ('KILOMETRAJE_MENOR', 'Kilometraje menor al anterior')], max_length=30, verbose_name='Tipo de alerta'),
        ),
    ]
