# Generated by Django 5.2.7 on 2026-04-10 21:25

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0008_alter_alertacombustible_tipo_alerta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='tipo_flujo',
            field=models.CharField(choices=[('FORANEO', 'Foráneo / Completo'), ('LOCAL', 'Local / Simplificado')], default='FORANEO', max_length=10, verbose_name='Tipo de flujo de registro'),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='foto_candado_anterior',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.MediaStorage(), upload_to='combustible/candado_anterior/%Y/%m/', verbose_name='Foto candado anterior'),
        ),
        migrations.AlterField(
            model_name='cargacombustible',
            name='foto_tablero',
            field=models.ImageField(blank=True, null=True, storage=config.storage_backends.MediaStorage(), upload_to='combustible/tablero/%Y/%m/', verbose_name='Foto del tablero'),
        ),
    ]
