# Generated by Django 5.2.7 on 2026-04-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0009_cargacombustible_tipo_flujo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertacombustible',
            name='analisis_ia',
            field=models.TextField(blank=True, help_text='Interpretación generada automáticamente por el analizador estadístico', verbose_name='Análisis IA'),
        ),
        migrations.AddField(
            model_name='alertacombustible',
            name='datos_estadisticos',
            field=models.JSONField(blank=True, default=dict, help_text='μ, σ, z-score y valores de referencia usados para detectar la anomalía', verbose_name='Datos estadísticos'),
        ),
        migrations.AddField(
            model_name='alertacombustible',
            name='generada_por_ia',
            field=models.BooleanField(default=False, verbose_name='Generada por IA'),
        ),
        migrations.AddField(
            model_name='alertacombustible',
            name='score_riesgo',
            field=models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('CRITICO', 'Crítico')], max_length=10, verbose_name='Score de riesgo IA'),
        ),
        migrations.AlterField(
            model_name='alertacombustible',
            name='tipo_alerta',
            field=models.CharField(choices=[('CANDADO_ALTERADO', 'Candado Alterado'), ('CANDADO_VIOLADO', 'Candado Violado'), ('SIN_CANDADO', 'Sin Candado'), ('EXCESO_COMBUSTIBLE', 'Exceso de Combustible'), ('CANDADO_NO_COINCIDE', 'Candado no coincide con carga anterior'), ('KILOMETRAJE_MENOR', 'Kilometraje menor al anterior'), ('CONSUMO_ATIPICO', 'Consumo atípico vs. historial'), ('RENDIMIENTO_ANOMALO', 'Rendimiento fuera del rango histórico'), ('TIEMPO_CARGA_ATIPICO', 'Tiempo de carga inusual'), ('NIVEL_INCONSISTENTE', 'Nivel inicial inconsistente con litros cargados'), ('PATRON_DESPACHADOR', 'Patrón anómalo en despachador')], max_length=30, verbose_name='Tipo de alerta'),
        ),
    ]
