# Generated by Django 5.2.7 on 2026-08-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combustible', '0011_alertacombustible_frecuencia_irregular'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacombustible',
            name='costo_calculado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cantidad_litros × precio de diésel mensual vigente al completar la carga', max_digits=10, null=True, verbose_name='Costo calculado'),
        ),
    ]
