# Generated by Django 5.2.7 on 2025-12-08 16:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('taller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FACTURA', 'Producto Nuevo desde Factura'), ('TALLER_REPARADO', 'Pieza Reparada del Taller'), ('TALLER_RECICLADO', 'Pieza/Material para Reciclar del Taller'), ('AJUSTE', 'Ajuste Manual de Inventario')], max_length=20)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_entrada', models.DateTimeField(default=django.utils.timezone.now)),
                ('factura_numero', models.CharField(blank=True, max_length=50)),
                ('factura_archivo', models.FileField(blank=True, null=True, upload_to='almacen/facturas/')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True)),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_almacen', to='compras.ordencompra')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entradas_almacen', to='taller.ordentrabajo')),
                ('recepcion_almacen_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_almacen_nuevo', to='compras.recepcionalmacen')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de Almacén',
                'verbose_name_plural': 'Entradas de Almacén',
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='ProductoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('subcategoria', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(help_text='Código SKU único', max_length=50, unique=True)),
                ('codigo_barras', models.CharField(blank=True, help_text='Código de barras (opcional)', max_length=50, null=True, unique=True)),
                ('descripcion', models.TextField()),
                ('localidad', models.CharField(help_text='Ubicación física en almacén (ej: Pasillo A, Estante 3)', max_length=100)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, help_text='Cantidad actual en inventario', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unidad_medida', models.CharField(help_text='Ej: Pieza, Litro, Kg, Caja, Metro', max_length=50)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Stock mínimo antes de generar alerta', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_maximo', models.DecimalField(decimal_places=2, default=0, help_text='Stock máximo recomendado', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('tiene_caducidad', models.BooleanField(default=False, help_text='Indica si el producto tiene fecha de caducidad')),
                ('fecha_caducidad', models.DateField(blank=True, help_text='Fecha de caducidad (si aplica)', null=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del producto', null=True, upload_to='almacen/productos/')),
                ('tiempo_reorden_dias', models.IntegerField(default=7, help_text='Días estimados para reabastecimiento', validators=[django.core.validators.MinValueValidator(1)])),
                ('notas', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto_compra', models.ForeignKey(blank=True, help_text='Vínculo con catálogo de compras', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_almacen', to='compras.producto')),
                ('proveedor_principal', models.ForeignKey(blank=True, help_text='Proveedor principal de este producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_almacen', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Producto de Almacén',
                'verbose_name_plural': 'Productos de Almacén',
                'ordering': ['categoria', 'subcategoria', 'descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ItemSolicitudSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True)),
                ('producto_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_salida', to='almacen.productoalmacen')),
            ],
            options={
                'verbose_name': 'Item de Solicitud de Salida',
                'verbose_name_plural': 'Items de Solicitud de Salida',
                'ordering': ['solicitud', 'producto_almacen'],
            },
        ),
        migrations.CreateModel(
            name='ItemEntradaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('costo_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('ubicacion_asignada', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='almacen.entradaalmacen')),
                ('producto_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='almacen.productoalmacen')),
            ],
            options={
                'verbose_name': 'Item de Entrada',
                'verbose_name_plural': 'Items de Entrada',
                'ordering': ['entrada', 'producto_almacen'],
            },
        ),
        migrations.CreateModel(
            name='AlertaStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('STOCK_MINIMO', 'Stock Mínimo Alcanzado'), ('STOCK_AGOTADO', 'Stock Agotado'), ('PROXIMO_CADUCAR', 'Próximo a Caducar'), ('CADUCADO', 'Producto Caducado')], max_length=20)),
                ('mensaje', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_resueltas', to=settings.AUTH_USER_MODEL)),
                ('producto_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='almacen.productoalmacen')),
            ],
            options={
                'verbose_name': 'Alerta de Stock',
                'verbose_name_plural': 'Alertas de Stock',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='SalidaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('entregado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_recibidas', to=settings.AUTH_USER_MODEL)),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_entregadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Salida de Almacén',
                'verbose_name_plural': 'Salidas de Almacén',
                'ordering': ['-fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('TRASLADO', 'Traslado')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_posterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_movimiento', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('entrada_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='almacen.entradaalmacen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_almacen', to=settings.AUTH_USER_MODEL)),
                ('producto_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='almacen.productoalmacen')),
                ('salida_almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='almacen.salidaalmacen')),
            ],
            options={
                'verbose_name': 'Movimiento de Almacén',
                'verbose_name_plural': 'Movimientos de Almacén',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='ItemSalidaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('ubicacion_origen', models.CharField(blank=True, max_length=100)),
                ('item_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_entregados', to='almacen.itemsolicitudsalida')),
                ('producto_almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='almacen.productoalmacen')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='almacen.salidaalmacen')),
            ],
            options={
                'verbose_name': 'Item de Salida',
                'verbose_name_plural': 'Items de Salida',
                'ordering': ['salida', 'producto_almacen'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ORDEN_TRABAJO', 'Para Orden de Trabajo del Taller'), ('SOLICITUD_GENERAL', 'Solicitud General')], max_length=20)),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Autorización'), ('AUTORIZADA', 'Autorizada'), ('RECHAZADA', 'Rechazada'), ('ENTREGADA', 'Entregada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('justificacion', models.TextField(help_text='Motivo de la solicitud')),
                ('requiere_autorizacion', models.BooleanField(default=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('comentarios_autorizacion', models.TextField(blank=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_almacen', to='taller.ordentrabajo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_almacen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Salida',
                'verbose_name_plural': 'Solicitudes de Salida',
                'ordering': ['-fecha_solicitud'],
                'permissions': [('autorizar_salida_almacen', 'Puede autorizar salidas de almacén')],
            },
        ),
        migrations.AddField(
            model_name='salidaalmacen',
            name='solicitud_salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='almacen.solicitudsalida'),
        ),
        migrations.AddField(
            model_name='itemsolicitudsalida',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='almacen.solicitudsalida'),
        ),
        migrations.AddIndex(
            model_name='entradaalmacen',
            index=models.Index(fields=['tipo', '-fecha_entrada'], name='almacen_ent_tipo_6e317f_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaalmacen',
            index=models.Index(fields=['folio'], name='almacen_ent_folio_ba2be3_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaalmacen',
            index=models.Index(fields=['-fecha_entrada'], name='almacen_ent_fecha_e_e21ab2_idx'),
        ),
        migrations.AddIndex(
            model_name='productoalmacen',
            index=models.Index(fields=['sku'], name='almacen_pro_sku_f131b9_idx'),
        ),
        migrations.AddIndex(
            model_name='productoalmacen',
            index=models.Index(fields=['codigo_barras'], name='almacen_pro_codigo__3f65e2_idx'),
        ),
        migrations.AddIndex(
            model_name='productoalmacen',
            index=models.Index(fields=['categoria', 'subcategoria'], name='almacen_pro_categor_264d08_idx'),
        ),
        migrations.AddIndex(
            model_name='productoalmacen',
            index=models.Index(fields=['cantidad'], name='almacen_pro_cantida_2b4ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='productoalmacen',
            index=models.Index(fields=['fecha_caducidad'], name='almacen_pro_fecha_c_2246b6_idx'),
        ),
        migrations.AddIndex(
            model_name='productoalmacen',
            index=models.Index(fields=['activo'], name='almacen_pro_activo_de3598_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['producto_almacen', 'resuelta'], name='almacen_ale_product_e438f8_idx'),
        ),
        migrations.AddIndex(
            model_name='alertastock',
            index=models.Index(fields=['tipo_alerta', '-fecha_generacion'], name='almacen_ale_tipo_al_b2f962_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['producto_almacen', '-fecha_movimiento'], name='almacen_mov_product_6a1b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['tipo'], name='almacen_mov_tipo_d1a598_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoalmacen',
            index=models.Index(fields=['-fecha_movimiento'], name='almacen_mov_fecha_m_c91ebb_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudsalida',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='almacen_sol_estado_aceb95_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudsalida',
            index=models.Index(fields=['folio'], name='almacen_sol_folio_f38c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudsalida',
            index=models.Index(fields=['orden_trabajo'], name='almacen_sol_orden_t_a332f3_idx'),
        ),
        migrations.AddIndex(
            model_name='salidaalmacen',
            index=models.Index(fields=['-fecha_salida'], name='almacen_sal_fecha_s_950950_idx'),
        ),
        migrations.AddIndex(
            model_name='salidaalmacen',
            index=models.Index(fields=['folio'], name='almacen_sal_folio_39ecea_idx'),
        ),
    ]
