# Generated by Django 5.1.2 on 2026-02-16 19:24

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productoalmacen',
            name='es_consumible',
            field=models.BooleanField(default=False, help_text='Indica si es un producto consumible de taller (trapos, gasolina blanca, desengrasante, etc.)'),
        ),
        migrations.CreateModel(
            name='SalidaRapidaConsumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('solicitante', models.CharField(help_text='Nombre de quien solicita el consumible', max_length=200)),
                ('motivo', models.CharField(help_text='Motivo o uso del consumible', max_length=500)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas_rapidas_entregadas', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(limit_choices_to={'activo': True, 'es_consumible': True}, on_delete=django.db.models.deletion.CASCADE, related_name='salidas_rapidas', to='almacen.productoalmacen')),
            ],
            options={
                'verbose_name': 'Salida Rápida de Consumible',
                'verbose_name_plural': 'Salidas Rápidas de Consumibles',
                'ordering': ['-fecha_salida'],
                'indexes': [models.Index(fields=['-fecha_salida'], name='almacen_sal_fecha_s_21b472_idx'), models.Index(fields=['folio'], name='almacen_sal_folio_780624_idx'), models.Index(fields=['producto'], name='almacen_sal_product_51257d_idx')],
            },
        ),
    ]
