# Generated by Django 5.1.2 on 2026-02-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_productoalmacen_es_consumible_salidarapidaconsumible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidarapidaconsumible',
            name='motivo',
            field=models.CharField(blank=True, help_text='Motivo o uso del consumible (opcional)', max_length=500),
        ),
    ]
