# Generated by Django 5.1.2 on 2026-02-16 23:45

import config.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_alter_salidarapidaconsumible_motivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaalmacen',
            name='factura_archivo',
            field=models.FileField(blank=True, null=True, storage=config.storage_backends.MediaStorage(), upload_to='almacen/facturas/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productoalmacen',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen del producto', null=True, storage=config.storage_backends.MediaStorage(), upload_to='almacen/productos/%Y/%m/'),
        ),
    ]
