# Generated by Django 5.2.8 on 2026-02-17 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_alter_entradaalmacen_factura_archivo_and_more'),
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidarapidaconsumible',
            name='unidad',
            field=models.ForeignKey(blank=True, help_text='Unidad a la que se asigna el consumible (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumibles_asignados', to='unidades.unidad'),
        ),
    ]
