# Generated by Django 5.2.7 on 2026-02-26 22:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_add_unidad_to_salida_rapida'),
        ('unidades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionDirectaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('motivo', models.CharField(help_text='Descripción de la reparación o motivo de la asignación', max_length=500)),
                ('observacion_interna', models.TextField(blank=True, help_text='Observación interna (solo visible para superusuarios)')),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('entregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_directas_almacen', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(limit_choices_to={'activo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_directas', to='almacen.productoalmacen')),
                ('unidad', models.ForeignKey(help_text='Unidad a la que se asigna la pieza', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_almacen', to='unidades.unidad')),
            ],
            options={
                'verbose_name': 'Asignación Directa de Almacén',
                'verbose_name_plural': 'Asignaciones Directas de Almacén',
                'ordering': ['-fecha_asignacion'],
                'indexes': [models.Index(fields=['-fecha_asignacion'], name='almacen_asi_fecha_a_86419c_idx'), models.Index(fields=['folio'], name='almacen_asi_folio_4b9407_idx'), models.Index(fields=['unidad', '-fecha_asignacion'], name='almacen_asi_unidad__9afd63_idx'), models.Index(fields=['producto'], name='almacen_asi_product_b108c9_idx')],
            },
        ),
    ]
