# Generated by Django 5.2.7 on 2026-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_asignaciondirectaalmacen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entradaalmacen',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA_DIRECTA', 'Entrada Directa'), ('FACTURA', 'Producto Nuevo desde Factura'), ('TALLER_REPARADO', 'Pieza Reparada del Taller'), ('TALLER_RECICLADO', 'Pieza/Material para Reciclar del Taller'), ('AJUSTE', 'Ajuste Manual de Inventario')], max_length=20),
        ),
    ]
