# Generated by Django 5.2.7 on 2026-05-15 22:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_entrada_directa_tipo'),
        ('caja_seca', '0001_initial'),
        ('dollys', '0001_initial'),
        ('equipos', '0001_initial'),
        ('unidades', '0002_unidad_control_combustible_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(editable=False, max_length=20, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('solicitante', models.CharField(max_length=150)),
                ('tipo_destino', models.CharField(choices=[('UNIDAD', 'Unidad'), ('EQUIPO', 'Equipo'), ('DOLLY', 'Dolly'), ('CAJA_SECA', 'Caja Seca'), ('OTRO', 'Otro')], max_length=10)),
                ('otro_destino', models.CharField(blank=True, max_length=200)),
                ('justificacion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja_seca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_salida', to='caja_seca.cajaseca')),
                ('dolly', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_salida', to='dollys.dolly')),
                ('entregado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_salida_almacen', to=settings.AUTH_USER_MODEL)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_salida', to='equipos.equipo')),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_salida', to='unidades.unidad')),
            ],
            options={
                'verbose_name': 'Asignación de Salida',
                'verbose_name_plural': 'Asignaciones de Salida',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemAsignacionSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('observaciones', models.CharField(blank=True, max_length=300)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='almacen.asignacionsalida')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_asignacion_salida', to='almacen.productoalmacen')),
            ],
            options={
                'verbose_name': 'Ítem de Asignación de Salida',
                'verbose_name_plural': 'Ítems de Asignación de Salida',
            },
        ),
        migrations.AddIndex(
            model_name='asignacionsalida',
            index=models.Index(fields=['folio'], name='almacen_asi_folio_ae2d9b_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionsalida',
            index=models.Index(fields=['-creado_en'], name='almacen_asi_creado__aa646f_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionsalida',
            index=models.Index(fields=['tipo_destino'], name='almacen_asi_tipo_de_942007_idx'),
        ),
    ]
