# Generated by Django 5.2.7 on 2026-06-30 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_asignacionsalida_itemasignacionsalida_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('AUTORIZAR', 'Autorizar'), ('RECHAZAR', 'Rechazar'), ('ENTREGAR', 'Entregar'), ('CANCELAR', 'Cancelar')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.CharField(max_length=100)),
                ('objeto_str', models.CharField(max_length=300)),
                ('valores_anteriores', models.JSONField(blank=True, null=True)),
                ('valores_nuevos', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_almacen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría de Almacén',
                'verbose_name_plural': 'Auditorías de Almacén',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='almacen_aud_fecha_36036b_idx'), models.Index(fields=['usuario'], name='almacen_aud_usuario_936680_idx'), models.Index(fields=['accion'], name='almacen_aud_accion_c1f88b_idx'), models.Index(fields=['modelo', '-fecha'], name='almacen_aud_modelo_915605_idx')],
            },
        ),
    ]
